version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/flask-app

hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root
    - location: scripts/install_codedeploy_agent.sh
      timeout: 300
      runas: root
    - location: scripts/configure_cloudwatch.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: startup.sh
      timeout: 300
      runas: root

